---
title: "Introducción a la Bioinformática"
author: "Mariette Viladomat Jasso"
date: "January 15, 2019"
---

# Introducción a la investigación reproducible

### Biología y computadoras:

__Biología Computacional:__ estudio de la biología utilizando cómputo. Su objetivo es generar conocimiento biológico, utilizando herramientas computacionales y código generado por alguien más para contestar tus preguntas.

__Bioinformática:__ creación de herramientas (algoritmos, software) para solucionar problemas puntuales con datos biológicos. Uno puede generar sus propias herramientas para contestar sus preguntas. Lo ideal es hacer disponible el código para que otra persona pueda contestar esa misma pregunta con sus datos.

__Investigación:__ La mayoría de la investigación que se publica recientemente utilizó una mezcla de los programas de alguien más (sobretodo en los primeros pasos del procesamiento de datos) y después se utilizan funciones propias para realizar análisis más específicos. Aunque la Biología Computacional y la Bioinformática no son lo mismo, tienen mucho en común y se apreden juntas. 

De aquí en adelante me referiré a análisis bioinformáticos, pero implica ambos tipos de disciplinas.

__Desafíos de la bioinformática__

• Grandes Volúmenes de información 
• Bases de datos heterogéneas y dispersas 
• Diferentes estándares tecnológicos
• Búsquedas extendidas y complejas 
• Gráficas avanzadas en 2D y 3D 
• Colaboración de equipos de investigadores interdisciplinarios 
• Formación de código nuevo (formación de bioinformáticos que aporten a la resolución de problemas)

### La crisis de reproducibilidad



### Contenedores

__Retos al reproducir pipelines de trabajos con tus datos propios:__

Las pipelines de trabajo bioinformáticos ocupan muchos programas distintos que constantemente están renovándose y actualizándose. La probabilidad de que tengamos una versión de algo distinto a la que corrieron los autores originales es muy alta, por lo que también es importante documentar la versión de los programas al usarlos.

Para poder utilizar estos programas de _código abierto_, se necesita de un software especializado como el de GNU/Linux, lo cuál puede no ser algo trivial de instalar (tal vez ustedes ya puedan compartirse anécdotas chistosas al respecto). Además, al instalar un programa bioinformático es común "romper" las dependencias de otro programa o incluso tu sistema operativo. 

REFERENCIA DE FOTO CHISTOSA  ¿Cómo funciona el sistema de carpetas basal de Linux?

Por eso a la hora de tener que hacer una actualización o reinstalación, el miedo nos invade.

Una solución a nuestros miedos más grandes puede ser el uso de __contenedores de software__. Un contenedor es una versión de un software (por ejemplo Linux) reducida a sus componentes más básicos. Ejemplos de contenedores:

Docker

K






### ¿Cómo buscar ayuda?

El objetivo de esta clase no es darte un manual completo para resolver cualquier cuestión bioinformática, sino darte las _habilidades y herramientas_ para que llegues por tí misma a las soluciones. Para esto hay una habilidad indispensable: buscar ayuda en internet. La enorme mayoría de las preguntas que te hagas sobre bioinformática y programación en general, sobre todo al principio, son las mismas dudas que tuvieron otros antes y, casi seguro las respuestas ya están en algún lugar del internet. Y si nadie ha tenido la misma duda, puedes preguntar.

Aprender a buscar soluciones en internet está perfectamente bien y es muy distinto a copiarle a un compañero. Saber buscar ayuda e información en interent es una habilidad básica del siglo XXI.


UNA REFERENCIA CHIDA



__([Stacksoverflow]https://stackoverflow.com/):__ es un foro de ayuda para programación en general, viene dividido por lenguajes. La gente hace preguntas y contesta. Es como un yahoo answers super pro, lxs programadorxs con muchas preguntas respondidas ganan puntos que son algo muy visible para un CV con ese perfil. Este foro es mejor para dudas de bash, R, python y no de programas genéticos.

__([Biostars]https://www.biostars.org/)__ es parecido a Stacksoverflow un foro de ayuda especializado en Bioinformática. Aquí sí puedes hacer preguntas enfocadas en datos y software genético, por ejemplo cómo mover de un formato de genomas a otro.

__Grupos de usuarios de un software.__ Por ejemplo ([este de Stacks]https://groups.google.com/forum/#!forum/stacks-users). Son ideales para aclarar detalles específicos y mensajes de error de ese software (ie, no de dudas de cómo usar la línea de comando). La comunidad es súper chida y muchas veces lxs autores del software son quiénes responden.



Tips sobre cómo pedir/buscar ayuda

1. Busca en inglés

2. Piensa bien cuáles son las palabras clave de tu pregunta y cómo generalizar tu caso a algo que cualquiera entienda y que no sea específico a tu computadora. Por ejemplo "How to list files in a directory using the Terminal?" es mucho mejor mejor que "which files are in Manzanas" (tu y yo sabemos que Manzanas es un directorio, pero no el mundo).

3. Si vas a pedir ayuda en un foro, lee las reglas y tipo de preguntas atentidas por el foro antes de preguntar.

4. Sigue estas recomendaciones de Stacksoverflow sobre ([cómo redactar una buena pregunta]https://stackoverflow.com/help/how-to-ask)

5. Si recibes un mensaje de error en la Terminal, R, etc. Copia-pégalo a tu motor de búsqueda favorito.








