---
title: "Introduccion_Metagenomica"
author: "Mariette Viladomat Jasso"
date: "January 15, 2019"
---

La metagenómica se ha definido como "el análisis genómico de microorganismos" por extracción directa y clonación de ADN de una comunidad o una muestra de un agregado de microorganismos ([Handelsman 2004](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.333.6836&rep=rep1&type=pdf)). Uno de los trabajos pioneros en el análisis de metagenómica se realizó por [Venter et al.](http://science.sciencemag.org/content/304/5667/66) en el Mar de los Sargazos. 


La metagenómica permite acceder al genoma sin ver a los microorganismos ni cultivarlos. Esta posibilidad de secuenciar directamente los genomas de microbios, sin necesidad de cultivarlos abre nuevas posibilidades que suponen un cambio de rumbo en la Microbiología. Este hecho es una revolución científica debido a su alto rendimiento y el bajo coste. 


Uno de los objetivos más importantes de los estudios metagenómicos es __la caracterización completa de una comunidad__, por lo que generalmente se requieren esfuerzos para __comprender: 1) la composición/estructura de la comunidad, incluyendo el desglose taxonómico y la abundancia relativa de las diversas especies, 2) contribución génica de cada miembro de la comunidad, incluyendo el número y capacidad funcional, y 3) la heterogeneidad de los genes dentro de la especie o dentro de la población__. 



La principal variante de laboratorio para obtener una comparación entre muestreos metagenómicos se observa en el tipo de datos moleculares que se utilizan para el estudio: __diferentes tipos de _amplicones_ (Tabla 1) o _datos tipo shotgun___. 

| Target        | Gen/Región         | Base de Datos                |
| ------------- |:------------------:| ----------------------------:|
| Bacteria      |         16S        | RDP,Greengenes, SILVA        |
| Arquea        |         16S        | RDP,Greengenes, SILVA        |
| Fungi         |      ITS, 18S      | UNITE, GenBank, BOLD, SILVA  |
| Protistas     |    ITS, 18S, COI   | SILVA, GenBank, BOLD         |
| Macrofauna    | COI, 16S, 12S, 18S | BOLD, GenBank                |
| Plantas       |  matK, + rbcL, ITS | BOLD, GenBank                |

_Tabla1. Diferentes tipos de marcadores usados en metagenómica en el estudio con amplicones ([Creer et al., 2016](https://besjournals.onlinelibrary.wiley.com/doi/pdf/10.1111/2041-210X.12574))._


__Los amplicones son muy útiles__ cuando se desea únicamente conocer la __presencia o ausencia de organismos en la comunidad muestreada__,  así como los __índices de diversidad taxonómica__ de dichos organismos([Kreisinger et al, 2017](https://www.frontiersin.org/articles/10.3389/fmicb.2017.00050/full)). Las __ventajas al usar marcadores conocidos__ para estos estudios __es lo bien anotadas que están las bases de datos y la cantidad de [programas especializados](http://www.bushmanlab.org/assets/pdf/publications/20383131.pdf) para generar los resultados sin quimeras__. 

__Sin embargo__, los amplicones __no permiten observar el potencial metabólico de la comunidad. Para tener esa información__  biológica, __se requiere__ todo el ADN de todos los organismos en la muestra: __datos tipo shotgun__ ([White III et al, 2015](https://www.researchgate.net/publication/282431849_Metagenomic_analysis_reveals_that_modern_microbialites_and_polar_microbial_mats_have_similar_taxonomic_and_functional_potential)). Idealmente, a partir de datos metagenómicos tipo shotgun, uno sería capaz inclusive de reconstruir completamente todos los genomas dentro de una muestra dada. Sin embargo, este objetivo particular ha sido en gran medida inalcanzable debido a limitaciones tecnológicas en el aislamiento bacteriano/recuperación del ADN así como en la capacidad de secuenciación (costo y rendimiento). ([Scholz, 2012](https://www.sciencedirect.com/science/article/pii/S0958166911007245)). Hasta ahora, sólo se ha podido reconstruir (a partir de inferencias) los genomas de los microorganismos más abundantes (con mayor repetido de lecturas en  la secuenciación) en una muestra poco compleja o con una cantidad total de reads muy alta.




